default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: qwer4321
  host: db

development:
  <<: *default
  database: kodacamp

test:
  <<: *default
  database: kodacamp_test


